### ISSUE TITLE
AYON_SERVER_URL can't use hostnames

### ISSUE THREAD

**Issue by EmberLightVFX** [ynput/ash#5]
I'm trying to host an ASH and for the var AYON_SERVER_URL I used the hostname for my server `http://server:5000` but I only got the error that it wasn't able to connect. In the end I had to use the hard-coded ip `http://192.168.101.70:5000` for it to fully work.

Being able to use a hostname instead of ip would make it more stable if for some reason the ip would change.

**Comment by EmberLightVFX** [comment]
I removed the ash container and image and re-created it to make sure I'm running 0.3.0 but still getting the same error.
This is how my compose looks like:
```
  worker:
    hostname: kitsuworker
    image: ynput/ayon-ash:latest
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "AYON_API_KEY=veryinsecurapikey"
      - "AYON_SERVER_URL=http://server:5000"
```

The api key is set correct and do work if I use the ip instead of the hostname `server`
